[package]
name = "dino-park-packs"
version = "0.5.0"
authors = ["Florian Merz <flomerz@gmail.com>"]
edition = "2018"

[lib]
path = "src/lib.rs"

[[bin]]
name = "dino-park-packs"
path = "src/main.rs"

[features]
default = []
local = ["dino_park_gate/localuserscope"]

[dependencies]
cis_client = { git = "https://github.com/mozilla-iam/cis_client-rust", branch = "0.7", version = "0.7" }
cis_profile = { git = "https://github.com/mozilla-iam/cis_profile-rust", branch = "0.4", version = "0.4", features = ["aws", "vendored"] }
dino_park_gate = { git = "https://github.com/mozilla-iam/dino-park-gate", tag = "0.7.2", version = "0.7" }
dino_park_trust = { git = "https://github.com/mozilla-iam/dino-park-trust", tag = "0.0.7", version = "0.0.7" }
dino_park_guard = { git = "https://github.com/mozilla-iam/dino-park-guard", tag = "0.2.3", version = "0.2" }
diesel = { version = "1.4", features = ["postgres", "uuidv07", "r2d2", "chrono", "serde_json"] }
diesel_migrations = "1.4"
actix-web = "2.0"
actix-rt = "1.0"
actix-multipart = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "0.8", features = ["serde", "v4"] }
log = "0.4"
env_logger = "0.7"
failure = "0.1"
failure_derive = "0.1"
diesel-derive-enum = { version = "0.4", features = ["postgres"] }
futures = "0.3"
r2d2 = "0.8"
config = "0.10"
chrono = "0.4"
rusoto_core = "0.44"
rusoto_ses = "0.44"
lazy_static = "1.4"

[dev-dependencies]
tokio = "0.2"
url = "2.1"
uuid = { version = "0.8", features = ["v5"] }
base64 = "0.12"
actix-http = "1.0"