name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  DPP_PG_URL: postgres://postgres:passw@localhost:5432/dino-park-packs-test-1

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: passw
          POSTGRES_DB: dino-park-packs-test-gha
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Run fmt
      run: cargo fmt --all -- --check
    - name: Clippy
      run: cargo clippy --all --all-features -- -D warning
    - name: Build
      run: cargo build --all --all-features --verbose
    - name: Run tests
      run: cargo test --all --features local -- --test-threads=1 --nocapture

